### ISSUE TITLE
Rework overview page

### ISSUE THREAD

**Issue by sykaeh** [django-girls-switzerland/static-website-tutorial-english#1]
Add numbers to steps:

0. Preparation (before Workshop)
   * Installation of Python, Git, Atom, Github Account
   * How the Internet works
1. Command Line Intensiv! (ca 1h) (Saturday morning)
2. Statische Webseite
   * Introduction (Statisch vs dynamisch)
   * Tools (git und github erklärt)
   * Preparation (workspace vorbereiten git projekt, ordner etc)
   * First message to the world (GIT)
   * Intro HTML
   * Intro CSS
3. Python (Saturday afternoon)
4. Django (and Deploy) (Sunday)
   * …
   * Adding your static page to Django (Metatutorial)
   * …

**Comment by KatuBeltz** [comment]
Pull Request opened ( #10 )

Didn't move the point 'Adding your static page to Django' to the chapter "4. Django" yet, becaue I wasn't sure anymore how we planned to do that. So I left it in the "Extras" part for now.
