### ISSUE TITLE
Change username to: django-girls-switzerland

### ISSUE THREAD

**Issue by django-girls-switzerland** [django-girls-switzerland/static-website-tutorial-english#18]
... if possible :)

and check if gitbook name changes too :)

**Comment by KatuBeltz** [comment]
done!

Now everyone need to update the remote url locally (here's how if you are in doubt: https://help.github.com/articles/changing-a-remote-s-url/).

Gitbook did not change the username yet. But maybe after the next merge when it syncs again.
