### ISSUE TITLE
Create preparation page

### ISSUE THREAD

**Issue by sykaeh** [django-girls-switzerland/static-website-tutorial-english#5]
Create a separate preparation step (*Step 0. from overview page*):

* Installation of the following (can be copied from: https://tutorial.djangogirls.org/en/installation/)
  * Python
  * Git
  * Code Editor (Atom)
* Create GitHub account
* How the internet works (link to: https://tutorial.djangogirls.org/en/how_the_internet_works/)

**Comment by django-girls-switzerland** [comment]
--> Pull request #12
